volumes:
  open-webui:
  searxng:
  redis-data:
  postgres-data:




networks:
  company_ai_network:
    driver: bridge

version: '3'
services:
  openwebui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    restart: always
    networks:
      - company_ai_network
    ports:
      - "3000:8080"
    volumes:
      - open-webui:/app/backend/data
    environment:
      - WEBUI_SECRET_KEY=${WEBUI_SECRET_KEY}  # F체r Sessions
      - LOG_LEVEL=INFO                        # Debugging
      - DISABLE_SIGNUP=True                   # Registrierung steuern
      - WEBUI_NAME=${WEBUI_NAME}
      - ENABLE_OPENAI_API=true
      - OPENAI_API_KEY=${IONOS_TOKEN} #das ist nicht OpenAI sondern Ionos
      - OPENAI_BASE_URL=${IONOS_BASE_URL}
      # Redis Konfiguration
      - REDIS_URL=redis://:${REDIS_PASSWORD:-your_secure_password}@redis:6379/0
      - WEBSOCKET_MANAGER=redis
      - WEBSOCKET_REDIS_URL=redis://:${REDIS_PASSWORD:-your_secure_password}@redis:6379/0
      - ENABLE_WEBSOCKET_SUPPORT=true
      # PostgreSQL Konfiguration (lokale DB f체r Test)
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/openwebui
      - DATABASE_POOL_SIZE=50
      - DATABASE_POOL_MAX_OVERFLOW=20
      - DATABASE_POOL_TIMEOUT=60
      - DATABASE_POOL_RECYCLE=1800
      - DATABASE_POOL_PRE_PING=true
      # LDAP Konfiguration (Microsoft Entra ID) - AUSKOMMENTIERT
      #- ENABLE_LDAP=true
      #- LDAP_SERVER=ldaps://login.microsoftonline.com
      #- LDAP_PORT=636
      #- LDAP_BASE_DN=DC=yourdomain,DC=com
      #- LDAP_BIND_DN=CN=ServiceAccount,DC=yourdomain,DC=com
      #- LDAP_BIND_PASSWORD=${LDAP_BIND_PASSWORD}
      #- LDAP_USER_SEARCH_BASE=DC=yourdomain,DC=com
      #- LDAP_USER_SEARCH_FILTER=(sAMAccountName={username})
      #- LDAP_USER_ATTRIBUTES=mail,displayName,memberOf
      #- LDAP_GROUP_SEARCH_BASE=DC=yourdomain,DC=com
      #- LDAP_GROUP_SEARCH_FILTER=(objectClass=group)
      #- LDAP_GROUP_ATTRIBUTES=cn,member
      #- LDAP_ADMIN_GROUP=CN=OpenWebUI-Admins,DC=yourdomain,DC=com

    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:16-alpine
    container_name: postgres
    restart: always
    networks:
      - company_ai_network
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=openwebui
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  nginx:
    image: nginx:mainline
    container_name: nginx
    ports:
      - "0.0.0.0:80:80"
      - "0.0.0.0:443:443"
    volumes:
      - ./conf.d:/etc/nginx/conf.d
      - ./ssl:/etc/nginx/ssl
    depends_on:
      - openwebui
      - searxng
    restart: unless-stopped
    networks:
      - company_ai_network
    environment:
      - WEBUI_NAME=owui

  searxng:
      image: searxng/searxng
      container_name: searxng
      restart: always
      networks:
        - company_ai_network
      ports:
        - "8081:8080"  # Ge채ndert auf 8081 um Konflikte zu vermeiden
      volumes:
        - searxng:/etc/searxng
        - ./settings.yml:/etc/searxng/settings.yml
      environment:
        - BASE_URL=http://searxng:8080/  # Ge채ndert auf den Container-Namen
        - INSTANCE_NAME=Safe Search Engine
        - UWSGI_WORKERS=4
        - UWSGI_THREADS=2

  redis:
    image: redis:7-alpine
    container_name: redis
    restart: always
    networks:
      - company_ai_network
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: redis-server --requirepass ${REDIS_PASSWORD:-your_secure_password} --appendonly yes --maxmemory 4gb --maxmemory-policy allkeys-lru
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD:-your_secure_password}



































