volumes:
  open-webui:
  searxng:
  n8n:
  qdrant-data:
  #für production: eigentlich soll noch postgresql statt der sqlite für openwebui...und ggf. für n8n andere qdrant instanz als die für openwebui den chats..
  # und ggf. managed redis oder eigeneer container


networks:
  xx-network:
    driver: bridge

version: '3'
services:
  openwebui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    restart: always
    networks:
      - xx-network
    ports:
      - "3000:8080"
    volumes:
      - open-webui:/app/backend/data
    environment:
      - WEBUI_SECRET_KEY=${WEBUI_SECRET_KEY}  # Für Sessions
      - LOG_LEVEL=INFO                        # Debugging
      - DISABLE_SIGNUP=True                   # Registrierung steuern
      #- WEBUI_AUTH=${WEBUI_AUTH}
      - WEBUI_NAME=${WEBUI_NAME}
      #- WEBUI_URL=${WEBUI_URL}
      #- FRONTEND_BUILD_DIR=${FRONTEND_BUILD_DIR}
      - ENABLE_OPENAI_API=true
      - OPENAI_API_KEY=${IONOS_TOKEN} #das ist nicht OpenAI sondern Ionos
      - OPENAI_BASE_URL=${IONOS_BASE_URL}
      - EMBEDDINGS_PROVIDER=openai # das ist nur das Format der Daten die wir haben. Kommt nicht wirklich von openai
      #- EMBEDDINGS_MODEL=${EMBEDDINGS_MODEL}
      #- BYPASS_MODEL_ACCESS_CONTROL=true
      #- DEFAULT_MODELS=meta-llama/Meta-Llama-3.1-8B-Instruct
      #- AVAILABLE_MODELS=meta-llama/Meta-Llama-3.1-8B-Instruct
      #- MODEL_LIST_URL=https://openai.inference.de-txl.ionos.com/v1/models
      # Qdrant Konfiguration
      - VECTOR_DB=qdrant
      - QDRANT_URI=http://qdrant:6333
      - QDRANT_API_KEY=${QDRANT_API_KEY:-sfsfsfsfsfsfssf}
      - QDRANT_COLLECTION_NAME=openwebui
      - QDRANT_TIMEOUT=30
      - QDRANT_HEALTH_CHECK_URL=/collections
    depends_on:
      - qdrant
    env_file:
      - .env          # Für sensible Daten

  nginx:
    image: nginx:mainline
    container_name: nginx
    ports:
      - "0.0.0.0:80:80"
      - "0.0.0.0:443:443"
    volumes:
      - ./conf.d:/etc/nginx/conf.d
      - ./ssl:/etc/nginx/ssl
    depends_on:
      - openwebui
      - searxng
    restart: unless-stopped
    networks:
      - xx-network
    environment:
      - WEBUI_NAME=xx

  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant
    restart: always
    networks:
      - xx-network
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant-data:/qdrant/storage
    environment:
      - QDRANT_ALLOW_CORS=true

  searxng:
      image: searxng/searxng
      container_name: searxng
      restart: always
      networks:
        - zugchat-network
      ports:
        - "8081:8080"  # Geändert auf 8081 um Konflikte zu vermeiden
      volumes:
        - searxng:/etc/searxng
        - ./settings.yml:/etc/searxng/settings.yml
      environment:
        - BASE_URL=http://searxng:8080/  # Geändert auf den Container-Namen
        - INSTANCE_NAME=xx Search
        - UWSGI_WORKERS=4
        - UWSGI_THREADS=2
